-- =============================================================================
-- MOTTOMAP - SCRIPT DDL (CREATE TABLE)
-- Arquivo para importação no Oracle SQL Developer Data Modeler
-- =============================================================================

-- 1.1 Tabelas Auxiliares (Domínios)
CREATE TABLE T_MM_STATUS_MOTO (
    CD_STATUS_MOTO NUMBER(3) NOT NULL PRIMARY KEY,
    DS_STATUS VARCHAR2(50) NOT NULL
);

CREATE TABLE T_MM_TIPO_PROBLEMA (
    CD_TIPO_PROBLEMA NUMBER(3) NOT NULL PRIMARY KEY,
    DS_TIPO_PROBLEMA VARCHAR2(100) NOT NULL
);

CREATE TABLE T_MM_TIPO_MOVIMENTACAO (
    CD_TIPO_MOVIMENTACAO NUMBER(3) NOT NULL PRIMARY KEY,
    DS_TIPO_MOVIMENTACAO VARCHAR2(50) NOT NULL
);

CREATE TABLE T_MM_STATUS_POSICAO (
    CD_STATUS_POSICAO NUMBER(2) NOT NULL PRIMARY KEY,
    DS_STATUS_POSICAO VARCHAR2(20) NOT NULL
);

-- 1.2 Tabelas Principais
CREATE TABLE T_MM_MODELO (
    CD_MODELO NUMBER(8) NOT NULL PRIMARY KEY,
    NM_MODELO VARCHAR2(100) NOT NULL,
    DS_MARCA VARCHAR2(50) NOT NULL,
    NR_ANO NUMBER(4) NOT NULL
);

CREATE TABLE T_MM_FILIAL (
    CD_FILIAL NUMBER(8) NOT NULL PRIMARY KEY,
    NM_FILIAL VARCHAR2(150) NOT NULL,
    DS_ENDERECO VARCHAR2(255) NOT NULL,
    NM_CIDADE VARCHAR2(100) NOT NULL,
    SG_ESTADO VARCHAR2(2) NOT NULL,
    NR_LINHA NUMBER(4) NOT NULL,
    NR_COLUNA NUMBER(4) NOT NULL,
    QT_CAPACIDADE_MAX NUMBER(6) NOT NULL
);

CREATE TABLE T_MM_USUARIO (
    CD_USUARIO NUMBER(9) NOT NULL PRIMARY KEY,
    CD_FILIAL NUMBER(8) NOT NULL,
    NM_USUARIO VARCHAR2(150) NOT NULL,
    DS_EMAIL VARCHAR2(100) NOT NULL,
    DS_SENHA VARCHAR2(200) NOT NULL,
    DS_CARGO VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_USUARIO_FILIAL FOREIGN KEY (CD_FILIAL) REFERENCES T_MM_FILIAL(CD_FILIAL)
);

CREATE TABLE T_MM_POSICAO_PATIO (
    CD_POSICAO NUMBER(6) NOT NULL PRIMARY KEY,
    CD_FILIAL NUMBER(8) NOT NULL,
    CD_STATUS_POSICAO NUMBER(2) NOT NULL,
    CD_IDENTIFICACAO VARCHAR2(10) NOT NULL,
    NR_LINHA NUMBER(4) NOT NULL,
    NR_COLUNA NUMBER(4) NOT NULL,
    DS_AREA VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_POSICAO_FILIAL FOREIGN KEY (CD_FILIAL) REFERENCES T_MM_FILIAL(CD_FILIAL),
    CONSTRAINT FK_POSICAO_STATUS FOREIGN KEY (CD_STATUS_POSICAO) REFERENCES T_MM_STATUS_POSICAO(CD_STATUS_POSICAO)
);

CREATE TABLE T_MM_MOTO (
    CD_MOTO NUMBER(9) NOT NULL PRIMARY KEY,
    CD_FILIAL NUMBER(8) NOT NULL,
    CD_MODELO NUMBER(8) NOT NULL,
    CD_STATUS_MOTO NUMBER(3) NOT NULL,
    DS_PLACA VARCHAR2(8),
    DS_CHASSI VARCHAR2(17),
    CONSTRAINT FK_MOTO_FILIAL FOREIGN KEY (CD_FILIAL) REFERENCES T_MM_FILIAL(CD_FILIAL),
    CONSTRAINT FK_MOTO_MODELO FOREIGN KEY (CD_MODELO) REFERENCES T_MM_MODELO(CD_MODELO),
    CONSTRAINT FK_MOTO_STATUS FOREIGN KEY (CD_STATUS_MOTO) REFERENCES T_MM_STATUS_MOTO(CD_STATUS_MOTO)
);

CREATE TABLE T_MM_PROBLEMA (
    CD_PROBLEMA NUMBER(9) NOT NULL PRIMARY KEY,
    CD_MOTO NUMBER(9) NOT NULL,
    CD_USUARIO NUMBER(9) NOT NULL,
    CD_TIPO_PROBLEMA NUMBER(3) NOT NULL,
    DS_DESCRICAO VARCHAR2(255) NOT NULL,
    DT_REGISTRO DATE NOT NULL,
    ST_RESOLVIDO NUMBER(1) NOT NULL CHECK (ST_RESOLVIDO IN (0, 1)),
    CONSTRAINT FK_PROBLEMA_MOTO FOREIGN KEY (CD_MOTO) REFERENCES T_MM_MOTO(CD_MOTO),
    CONSTRAINT FK_PROBLEMA_USUARIO FOREIGN KEY (CD_USUARIO) REFERENCES T_MM_USUARIO(CD_USUARIO),
    CONSTRAINT FK_PROBLEMA_TIPO FOREIGN KEY (CD_TIPO_PROBLEMA) REFERENCES T_MM_TIPO_PROBLEMA(CD_TIPO_PROBLEMA)
);

CREATE TABLE T_MM_MOVIMENTACAO (
    CD_MOVIMENTACAO NUMBER(10) NOT NULL PRIMARY KEY,
    CD_USUARIO NUMBER(9) NOT NULL,
    CD_MOTO NUMBER(9) NOT NULL,
    CD_TIPO_MOVIMENTACAO NUMBER(3) NOT NULL,
    DT_HORA DATE NOT NULL,
    VL_MOVIMENTACAO NUMBER(10, 2) DEFAULT 0 NOT NULL,
    DS_OBSERVACOES VARCHAR2(255),
    CONSTRAINT FK_MOVIMENTACAO_USUARIO FOREIGN KEY (CD_USUARIO) REFERENCES T_MM_USUARIO(CD_USUARIO),
    CONSTRAINT FK_MOVIMENTACAO_MOTO FOREIGN KEY (CD_MOTO) REFERENCES T_MM_MOTO(CD_MOTO),
    CONSTRAINT FK_MOVIMENTACAO_TIPO FOREIGN KEY (CD_TIPO_MOVIMENTACAO) REFERENCES T_MM_TIPO_MOVIMENTACAO(CD_TIPO_MOVIMENTACAO)
);

CREATE TABLE T_MM_HISTORICO_POSICAO (
    CD_HISTORICO NUMBER(10) NOT NULL PRIMARY KEY,
    CD_MOTO NUMBER(9) NOT NULL,
    CD_POSICAO NUMBER(6) NOT NULL,
    DT_INICIO DATE NOT NULL,
    DT_FIM DATE,
    CONSTRAINT FK_HISTORICO_MOTO FOREIGN KEY (CD_MOTO) REFERENCES T_MM_MOTO(CD_MOTO),
    CONSTRAINT FK_HISTORICO_POSICAO FOREIGN KEY (CD_POSICao) REFERENCES T_MM_POSICAO_PATIO(CD_POSICao)
);

CREATE TABLE T_MM_CAMERA (
    CD_CAMERA NUMBER(6) NOT NULL PRIMARY KEY,
    CD_FILIAL NUMBER(8) NOT NULL,
    DS_MODELO_CAM VARCHAR2(100) NOT NULL,
    DS_LOCALIZACAO VARCHAR2(255) NOT NULL,
    IP_ADDRESS VARCHAR2(45),
    CONSTRAINT FK_CAMERA_FILIAL FOREIGN KEY (CD_FILIAL) REFERENCES T_MM_FILIAL(CD_FILIAL)
);

CREATE TABLE T_MM_CAPTURA_IMAGEM (
    CD_CAPTURA NUMBER(12) NOT NULL PRIMARY KEY,
    CD_CAMERA NUMBER(6) NOT NULL,
    CD_POSICAO_PATIO NUMBER(6),
    DT_CAPTURA TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DS_URL_IMAGEM VARCHAR2(512) NOT NULL,
    ST_PROCESSADA NUMBER(1) DEFAULT 0 NOT NULL CHECK (ST_PROCESSADA IN (0,1)),
    CONSTRAINT FK_CAPTURA_CAMERA FOREIGN KEY (CD_CAMERA) REFERENCES T_MM_CAMERA(CD_CAMERA),
    CONSTRAINT FK_CAPTURA_POSICAO FOREIGN KEY (CD_POSICAO_PATIO) REFERENCES T_MM_POSICAO_PATIO(CD_POSICAO)
);

CREATE TABLE T_MM_AUDITORIA (
    CD_AUDITORIA        NUMBER(10) NOT NULL PRIMARY KEY,
    NM_USUARIO          VARCHAR2(100),
    DT_OPERACAO         TIMESTAMP,
    NM_TABELA           VARCHAR2(30),
    DS_OPERACAO         VARCHAR2(10),
    DS_VALORES_ANTIGOS  CLOB,
    DS_VALORES_NOVOS    CLOB
);
