-- 1. CRIAÇÃO DAS TABELAS AUXILIARES (DOMÍNIOS FIXOS)
-- Tabelas criadas para normalizar campos que se repetiam como texto.

CREATE TABLE T_MM_STATUS_MOTO (
    CD_STATUS_MOTO NUMBER(3) NOT NULL,
    DS_STATUS      VARCHAR2(50) NOT NULL
);
ALTER TABLE T_MM_STATUS_MOTO ADD CONSTRAINT PK_STATUS_MOTO_MOTOMAP PRIMARY KEY (CD_STATUS_MOTO);

CREATE TABLE T_MM_TIPO_PROBLEMA (
    CD_TIPO_PROBLEMA NUMBER(3) NOT NULL,
    DS_TIPO_PROBLEMA VARCHAR2(100) NOT NULL
);
ALTER TABLE T_MM_TIPO_PROBLEMA ADD CONSTRAINT PK_TIPO_PROBLEMA_MOTOMAP PRIMARY KEY (CD_TIPO_PROBLEMA);

CREATE TABLE T_MM_TIPO_MOVIMENTACAO (
    CD_TIPO_MOVIMENTACAO NUMBER(3) NOT NULL,
    DS_TIPO_MOVIMENTACAO VARCHAR2(50) NOT NULL
);
ALTER TABLE T_MM_TIPO_MOVIMENTACAO ADD CONSTRAINT PK_TIPO_MOVIMENTACAO_MOTOMAP PRIMARY KEY (CD_TIPO_MOVIMENTACAO);

CREATE TABLE T_MM_STATUS_POSICAO (
    CD_STATUS_POSICAO NUMBER(2) NOT NULL,
    DS_STATUS_POSICAO VARCHAR2(20) NOT NULL
);
ALTER TABLE T_MM_STATUS_POSICao ADD CONSTRAINT PK_STATUS_POSICAO_MOTOMAP PRIMARY KEY (CD_STATUS_POSICAO);


-- 2. CRIAÇÃO DAS ENTIDADES PRINCIPAIS E NORMALIZADAS

-- Tabela para os modelos de moto, eliminando dependência transitiva na T_MM_MOTO.
CREATE TABLE T_MM_MODELO (
    CD_MODELO NUMBER(8) NOT NULL,
    NM_MODELO VARCHAR2(100) NOT NULL,
    DS_MARCA  VARCHAR2(50) NOT NULL,
    NR_ANO    NUMBER(4) NOT NULL
);
ALTER TABLE T_MM_MODELO ADD CONSTRAINT PK_MODELO_MOTOMAP PRIMARY KEY (CD_MODELO);

-- Tabela de Filial (sem alterações na estrutura)
CREATE TABLE T_MM_FILIAL (
    CD_FILIAL         NUMBER(8) NOT NULL,
    NM_FILIAL         VARCHAR2(150) NOT NULL,
    DS_ENDERECO       VARCHAR2(255) NOT NULL,
    NM_CIDADE         VARCHAR2(100) NOT NULL,
    SG_ESTADO         VARCHAR2(2) NOT NULL,
    NR_LINHA          NUMBER(4) NOT NULL,
    NR_COLUNA         NUMBER(4) NOT NULL,
    QT_CAPACIDADE_MAX NUMBER(6) NOT NULL
);
ALTER TABLE T_MM_FILIAL ADD CONSTRAINT PK_FILIAL_MOTOMAP PRIMARY KEY (CD_FILIAL);

-- Tabela de Usuário (sem alterações na estrutura)
CREATE TABLE T_MM_USUARIO (
    CD_USUARIO    NUMBER(9) NOT NULL,
    CD_FILIAL     NUMBER(8) NOT NULL,
    NM_USUARIO    VARCHAR2(150) NOT NULL,
    DS_EMAIL      VARCHAR2(100) NOT NULL,
    DS_SENHA      VARCHAR2(200) NOT NULL,
    DS_CARGO      VARCHAR2(20) NOT NULL
);
ALTER TABLE T_MM_USUARIO ADD CONSTRAINT PK_USUARIO_MOTOMAP PRIMARY KEY (CD_USUARIO);
ALTER TABLE T_MM_USUARIO ADD CONSTRAINT FK_CD_FILIAL_USUARIO FOREIGN KEY (CD_FILIAL) REFERENCES T_MM_FILIAL (CD_FILIAL);

-- Tabela Posição Pátio (Atualizada para usar a tabela de status)
CREATE TABLE T_MM_POSICAO_PATIO (
    CD_POSICAO        NUMBER(6) NOT NULL,
    CD_FILIAL         NUMBER(8) NOT NULL,
    CD_STATUS_POSICAO NUMBER(2) NOT NULL,
    CD_IDENTIFICACAO  VARCHAR2(10) NOT NULL,
    NR_LINHA          NUMBER(4) NOT NULL,
    NR_COLUNA         NUMBER(4) NOT NULL,
    DS_AREA           VARCHAR2(50) NOT NULL
);
ALTER TABLE T_MM_POSICAO_PATIO ADD CONSTRAINT PK_POSICAO_MOTOMAP PRIMARY KEY (CD_POSICAO);
ALTER TABLE T_MM_POSICAO_PATIO ADD CONSTRAINT FK_CD_FILIAL_POSICAO FOREIGN KEY (CD_FILIAL) REFERENCES T_MM_FILIAL (CD_FILIAL);
ALTER TABLE T_MM_POSICAO_PATIO ADD CONSTRAINT FK_STATUS_POSICAO FOREIGN KEY (CD_STATUS_POSICAO) REFERENCES T_MM_STATUS_POSICAO (CD_STATUS_POSICAO);

-- Tabela Moto (Atualizada para usar as tabelas de Modelo e Status)
CREATE TABLE T_MM_MOTO (
    CD_MOTO        NUMBER(9) NOT NULL,
    CD_FILIAL      NUMBER(8) NOT NULL,
    CD_MODELO      NUMBER(8) NOT NULL,
    CD_STATUS_MOTO NUMBER(3) NOT NULL,
    DS_PLACA       VARCHAR2(8),
    DS_CHASSI      VARCHAR2(17)
);
ALTER TABLE T_MM_MOTO ADD CONSTRAINT PK_MOTO_MOTOMAP PRIMARY KEY (CD_MOTO);
ALTER TABLE T_MM_MOTO ADD CONSTRAINT FK_CD_FILIAL_MOTO FOREIGN KEY (CD_FILIAL) REFERENCES T_MM_FILIAL (CD_FILIAL);
ALTER TABLE T_MM_MOTO ADD CONSTRAINT FK_MODELO_MOTO FOREIGN KEY (CD_MODELO) REFERENCES T_MM_MODELO (CD_MODELO);
ALTER TABLE T_MM_MOTO ADD CONSTRAINT FK_STATUS_MOTO FOREIGN KEY (CD_STATUS_MOTO) REFERENCES T_MM_STATUS_MOTO (CD_STATUS_MOTO);

-- Tabela Problema (Atualizada para usar a tabela de Tipo de Problema)
CREATE TABLE T_MM_PROBLEMA (
    CD_PROBLEMA      NUMBER(9) NOT NULL,
    CD_MOTO          NUMBER(9) NOT NULL,
    CD_USUARIO       NUMBER(9) NOT NULL,
    CD_TIPO_PROBLEMA NUMBER(3) NOT NULL,
    DS_DESCRICAO     VARCHAR2(255) NOT NULL,
    DT_REGISTRO      DATE NOT NULL,
    ST_RESOLVIDO     NUMBER(1) NOT NULL CHECK (ST_RESOLVIDO IN (0, 1)) -- Renomeado para ST_ (Status)
);
ALTER TABLE T_MM_PROBLEMA ADD CONSTRAINT PK_PROBLEMA_MOTOMAP PRIMARY KEY (CD_PROBLEMA);
ALTER TABLE T_MM_PROBLEMA ADD CONSTRAINT FK_MOTO_PROBLEMA FOREIGN KEY (CD_MOTO) REFERENCES T_MM_MOTO (CD_MOTO);
ALTER TABLE T_MM_PROBLEMA ADD CONSTRAINT FK_USUARIO_PROBLEMA FOREIGN KEY (CD_USUARIO) REFERENCES T_MM_USUARIO (CD_USUARIO);
ALTER TABLE T_MM_PROBLEMA ADD CONSTRAINT FK_TIPO_PROBLEMA FOREIGN KEY (CD_TIPO_PROBLEMA) REFERENCES T_MM_TIPO_PROBLEMA (CD_TIPO_PROBLEMA);

-- Tabela Movimentação (Atualizada para usar a tabela de Tipo de Movimentação)
CREATE TABLE T_MM_MOVIMENTACAO (
    CD_MOVIMENTACAO      NUMBER(10) NOT NULL,
    CD_USUARIO           NUMBER(9) NOT NULL,
    CD_MOTO              NUMBER(9) NOT NULL,
    CD_TIPO_MOVIMENTACAO NUMBER(3) NOT NULL,
    DT_HORA              DATE NOT NULL,
    DS_OBSERVACOES       VARCHAR2(255)
);
ALTER TABLE T_MM_MOVIMENTACAO ADD CONSTRAINT PK_MOVIMENTACAO_MOTOMAP PRIMARY KEY (CD_MOVIMENTACAO);
ALTER TABLE T_MM_MOVIMENTACAO ADD CONSTRAINT FK_USUARIO_MOVIMENTACAO FOREIGN KEY (CD_USUARIO) REFERENCES T_MM_USUARIO (CD_USUARIO);
ALTER TABLE T_MM_MOVIMENTACAO ADD CONSTRAINT FK_MOTO_MOVIMENTACAO FOREIGN KEY (CD_MOTO) REFERENCES T_MM_MOTO (CD_MOTO);
ALTER TABLE T_MM_MOVIMENTACAO ADD CONSTRAINT FK_TIPO_MOVIMENTACAO FOREIGN KEY (CD_TIPO_MOVIMENTACAO) REFERENCES T_MM_TIPO_MOVIMENTACAO (CD_TIPO_MOVIMENTACAO);

-- Tabela Histórico de Posição (sem alterações na estrutura)
CREATE TABLE T_MM_HISTORICO_POSICAO (
    CD_HISTORICO NUMBER(10) NOT NULL,
    CD_MOTO      NUMBER(9) NOT NULL,
    CD_POSICAO   NUMBER(6) NOT NULL,
    DT_INICIO    DATE NOT NULL,
    DT_FIM       DATE
);
ALTER TABLE T_MM_HISTORICO_POSICAO ADD CONSTRAINT PK_HISTORICO_MOTOMAP PRIMARY KEY (CD_HISTORICO);
ALTER TABLE T_MM_HISTORICO_POSICAO ADD CONSTRAINT FK_MOTO_HISTORICO FOREIGN KEY (CD_MOTO) REFERENCES T_MM_MOTO (CD_MOTO);
ALTER TABLE T_MM_HISTORICO_POSICAO ADD CONSTRAINT FK_POSICAO_HISTORICO FOREIGN KEY (CD_POSICAO) REFERENCES T_MM_POSICAO_PATIO (CD_POSICAO);


-- 3. CRIAÇÃO DAS TABELAS PARA O SISTEMA DE CÂMERAS COM IA
-- Novas entidades sugeridas para contemplar a funcionalidade de IA.

CREATE TABLE T_MM_CAMERA (
    CD_CAMERA      NUMBER(6) NOT NULL,
    CD_FILIAL      NUMBER(8) NOT NULL,
    DS_MODELO_CAM  VARCHAR2(100) NOT NULL,
    DS_LOCALIZACAO VARCHAR2(255) NOT NULL,
    IP_ADDRESS     VARCHAR2(45) -- Suporta IPv6
);
ALTER TABLE T_MM_CAMERA ADD CONSTRAINT PK_CAMERA_MOTOMAP PRIMARY KEY (CD_CAMERA);
ALTER TABLE T_MM_CAMERA ADD CONSTRAINT FK_FILIAL_CAMERA FOREIGN KEY (CD_FILIAL) REFERENCES T_MM_FILIAL (CD_FILIAL);

CREATE TABLE T_MM_CAPTURA_IMAGEM (
    CD_CAPTURA       NUMBER(12) NOT NULL,
    CD_CAMERA        NUMBER(6) NOT NULL,
    CD_POSICAO_PATIO NUMBER(6), -- Posição identificada pela IA
    DT_CAPTURA       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DS_URL_IMAGEM    VARCHAR2(512) NOT NULL,
    ST_PROCESSADA    NUMBER(1) DEFAULT 0 NOT NULL CHECK (ST_PROCESSADA IN (0,1)) -- 0: Não, 1: Sim
);
ALTER TABLE T_MM_CAPTURA_IMAGEM ADD CONSTRAINT PK_CAPTURA_IMAGEM_MOTOMAP PRIMARY KEY (CD_CAPTURA);
ALTER TABLE T_MM_CAPTURA_IMAGEM ADD CONSTRAINT FK_CAMERA_CAPTURA FOREIGN KEY (CD_CAMERA) REFERENCES T_MM_CAMERA (CD_CAMERA);
ALTER TABLE T_MM_CAPTURA_IMAGEM ADD CONSTRAINT FK_POSICAO_PATIO_CAPTURA FOREIGN KEY (CD_POSICAO_PATIO) REFERENCES T_MM_POSICAO_PATIO (CD_POSICAO);

COMMIT;