--Nome: Caike Dametto RM: 558614
--Nome: Guilhetme Janunzzi RM: 558461

DROP TABLE T_MM_CAPTURA_IMAGEM;
DROP TABLE T_MM_CAMERA;
DROP TABLE T_MM_HISTORICO_POSICAO;
DROP TABLE T_MM_MOVIMENTACAO;
DROP TABLE T_MM_PROBLEMA;
DROP TABLE T_MM_MOTO;
DROP TABLE T_MM_POSICAO_PATIO;
DROP TABLE T_MM_USUARIO;
DROP TABLE T_MM_FILIAL;
DROP TABLE T_MM_MODELO;
DROP TABLE T_MM_STATUS_MOTO;
DROP TABLE T_MM_TIPO_PROBLEMA;
DROP TABLE T_MM_TIPO_MOVIMENTACAO;
DROP TABLE T_MM_STATUS_POSICAO;